### ISSUE TITLE
Ubuntu install requires additional packages

### ISSUE THREAD

**Issue by mlangill** [dparks1134/STAMP#17]
I got an error when attempting to install STAMP in Ubuntu 15.10 using the directions outlined here: http://kiwi.cs.dal.ca/Software/Quick_installation_instructions_for_STAMP

During the 
`sudo pip install STAMP`
 I got the error
`'no lapack/blas resources fund'`

Installing the following packages fixed the error:
sudo apt-get install libblas-dev liblapack-dev gfortran

Suggest adding this to the install instructions.

**Comment by dparks1134** [comment]
Thanks. I've updated the wiki.
