### ISSUE TITLE
Is the command line interface gone?

### ISSUE THREAD

**Issue by geboro** [dparks1134/STAMP#19]
Hey, I just checked v.2.1.3 installed from the Ubuntu repository and couldn't find commandLine.py, which is supposed to give access to the command line interface... 
Could this be a repository issue?

**Comment by dparks1134** [comment]
The command line interface has been removed as it was challenging to maintained and was not widely used.

**Comment by geboro** [comment]
Ah that explains it... 
So is there any way to retrieve text/tsv tables of the active features after filtering?
thanks!

**Comment by dparks1134** [comment]
In the View menu, you can bring up tables of results and save these to file.
