### ISSUE TITLE
STAMP: PyQt 5 instead of pyQt4

### ISSUE THREAD

**Issue by nidhiv13** [dparks1134/STAMP#22]
Hi

The python in the common lab Linux is using pyqt5. I do not want to disturb anyone else's programs by uninstall pyqt5 and using pyqt4 instead. Is it possible to run STAMP with pyqt5?

Thanks

**Comment by dparks1134** [comment]
No, STAMP requires PyQt4. However, I believe you should be able to install this along side PyQt5.
