### ISSUE TITLE
PCA method:

### ISSUE THREAD

**Issue by EisenRa** [dparks1134/STAMP#25]
Dear authors,

Thank you for writing this software -- it is brilliant!

I have a quick question regarding the PCA analysis: how is the data ordinated? Bray-Curtis?

Kind regards,
Raphael

**Comment by dparks1134** [comment]
Just Euclidean.

**Comment by EisenRa** [comment]
Thanks! Presumably, pseudocounts are added to null values?

**Comment by dparks1134** [comment]
You can set the psedocount in one of STAMP's dialog boxes.
