### ISSUE TITLE
Script for along usage

### ISSUE THREAD

**Issue by LuffyLuffy** [dparks1134/STAMP#26]
Hi, Denovan,

STAMP is really a nice and friendly software for statistics.

I have 13 pairs samples for two-sample fisher's exact test. Since the command line has been removed from New version, it would be really a energy-consuming work. 
I wonder if it possible to get a stand-along script for the analysis and figure plotting. 

Although you have shared the code, however, I'm new to python, unable to extract the script for analysis repeatedly. I am only able to write some simple bash profile to run code. 

It would be highly appreciated if you can offer a stand-along scripts for the test and plots.

I'll try to learn more about python code. And hopefully to help a little.

**Comment by dparks1134** [comment]
Hello. I'm afraid I don't have a stand-alone script.
