### ISSUE TITLE
How to start STAMP from command line

### ISSUE THREAD

**Issue by emankhalaf** [dparks1134/STAMP#27]
Hello,
I am a beginner in using STAMP. I am using Ubuntu 16.04. I created an environment and installed stamp using the following code:
conda install -c bioconda stamp

I have my file generated from Tax4Fun comparing reads/values of metabolic pathways in a control sample vs pathogen-treated sample. I don't know how to use stamp from the command line.

I have a previous trial where I installed the software quickly on my pc, but the test file did not work that makes me uncertain about using it based on the installation instructions.

All what I need is a good tutorial for using STAMP from command line

Thanks
Eman

**Comment by emankhalaf** [comment]
I run: STAMP
and got this error:

Traceback (most recent call last):
  File "/home/eman/anaconda3/envs/stamp/bin/STAMP", line 32, in <module>
    from stamp import STAMP
  File "/home/eman/anaconda3/envs/stamp/lib/python2.7/site-packages/stamp/STAMP.py", line 38, in <module>
    from stamp.GUI.plotDlg import PlotDlg  # forward reference so py2app recognizes this file is required
  File "/home/eman/anaconda3/envs/stamp/lib/python2.7/site-packages/stamp/GUI/plotDlg.py", line 24, in <module>
    from PyQt4 import QtGui, QtCore
ImportError: No module named PyQt4

Actually, I have pyqt5 in the plugin folder. Does it mean I need to download pyqt4?
Please help

**Comment by emankhalaf** [comment]
solved.
Thanks

**Comment by GuillaumeSwB** [comment]
Hi,

Could you please tell me how did you solve it ?

**Comment by NainaK6** [comment]
Hi, could anyone please let me know, how can I run STAMP from the command line in a Linux cluster?

**Comment by limrp** [comment]
> Hi, could anyone please let me know, how can I run STAMP from the command line in a Linux cluster?

I have the same question. Does anyone has a solution for this?

**Comment by emankhalaf** [comment]
just type $stamp
