### ISSUE TITLE
v2.1.3 has  CLI in linux ?

### ISSUE THREAD

**Issue by orangeSi** [dparks1134/STAMP#29]
hi~ I want to know if stamp has a CLI (command line) in linux ?

Thanks~

**Comment by dparks1134** [comment]
No. The CLI was removed several versions ago.

**Comment by orangeSi** [comment]
thanks for the reply~ It mean I need to use STAMP as a python package in python code like biopython in linux ?

**Comment by orangeSi** [comment]
Is there other ways to run STAMP in linux instead of GUI or write python code?  Is xvfb-run able to do that ?

**Comment by dparks1134** [comment]
STAMP is intended to be run via the GUI. You might find something like ShotgunFunctionalizeR or one of the other common statistic packages more useful if you need a programmable interface.

**Comment by orangeSi** [comment]
Thanks a lot for your patient reply~
