### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by jzrapp** [dparks1134/STAMP#31]
Hi,

I would love to use stamp, but I'm really struggling with the installation. I have been trying to install on a macOS mojave system now for hours and end up facing different issues. This is one that I now come back to:
using a newly re-installed conda 4.7.12 version for python2.7:

conda install stamp
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                       

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package sqlite conflicts for:
python=2.7 -> sqlite[version='>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.27.2,<4.0a0|>=3.29.0,<4.0a0|>=3.30.0,<4.0a0']
Package zlib conflicts for:
python=2.7 -> zlib[version='>=1.2.11,<1.3.0a0']
Package ncurses conflicts for:
python=2.7 -> ncurses[version='>=6.0,<7.0a0|>=6.1,<7.0a0']
Package libcxx conflicts for:
python=2.7 -> libcxx[version='>=4.0.1']
Package six conflicts for:
stamp -> six[version='>=1.3']
Package openssl conflicts for:
python=2.7 -> openssl[version='1.0.*|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.1.1a,<1.1.2a']
Package pyqt conflicts for:
stamp -> pyqt[version='4.*|>=4.11.4,<4.12.0a0']
Package pyqi conflicts for:
stamp -> pyqi[version='>=0.3.2']
Package pip conflicts for:
python=2.7 -> pip
Package ca-certificates conflicts for:
python=2.7 -> ca-certificates
Package scipy conflicts for:
stamp -> scipy[version='>=0.15.1']
Package tk conflicts for:
python=2.7 -> tk[version='8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0']
Package biom-format conflicts for:
stamp -> biom-format[version='>=2.0.1']
Package libffi conflicts for:
python=2.7 -> libffi[version='3.2.*|>=3.2.1,<4.0a0']
Package readline conflicts for:
python=2.7 -> readline[version='7.*|>=7.0,<8.0a0']
Package numpy conflicts for:
stamp -> numpy[version='>=1.9.1']
Package matplotlib conflicts for:
stamp -> matplotlib[version='>=1.4.2']

Could you help with this? I also tried the pip install but also end up with errors...

Thanks a lot!

**Comment by dparks1134** [comment]
Hi. You might also try posting your question on the STAMP Google group:
http://kiwi.cs.dal.ca/Software/STAMP

I don't have any experience install STAMP on OS X so can't provide any direct help.

**Comment by jzrapp** [comment]
After 10 hours of frustration and multiple re-installation attempts of anaconda etc, I seem to have a working STAMP installation! 
Just wanted to share my steps in case someone else is about to lose its mind:

I reinstalled anaconda for python 2.7
and created a dedicated stamp environment, where I specified python 2.7:

conda create -n stamp python=2.7
conda activate stamp
pip install numpy

#Installing collected packages: numpy
#Successfully installed numpy-1.16.5

pip install STAMP
# Installing collected packages: six, pyparsing, backports.functools-lru-cache, subprocess32, python-dateutil, pytz, kiwisolver, cycler, matplotlib, scipy, pandas, future, click, pyqi, biom-format, 
# STAMP
# Successfully installed STAMP-2.1.3 backports.functools-lru-cache-1.6.1 biom-format-2.1.7 click-7.0 cycler-0.10.0 future-0.18.2 kiwisolver-1.1.0 matplotlib-2.2.4 pandas-0.24.2 pyparsing-2.4.5 pyqi-0.3.2 python-dateutil-2.8.1 pytz-2019.3 scipy-1.2.2 six-1.13.0 subprocess32-3.5.4

#Open new terminal session, enter STAMP to run.
conda activate stamp

STAMP
Traceback (most recent call last):
  File "/opt/anaconda2/envs/stamp/bin/STAMP", line 32, in <module>
    from stamp import STAMP
  File "/opt/anaconda2/envs/stamp/lib/python2.7/site-packages/stamp/STAMP.py", line 38, in <module>
    from stamp.GUI.plotDlg import PlotDlg  # forward reference so py2app recognizes this file is required
  File "/opt/anaconda2/envs/stamp/lib/python2.7/site-packages/stamp/GUI/plotDlg.py", line 24, in <module>
    from PyQt4 import QtGui, QtCore
ImportError: No module named PyQt4

###STILL THE SAME ERROR! 
#change pygt version. Used the asmeurer channel:

conda install -n stamp -c asmeurer pyqt=4
# Collecting package metadata (current_repodata.json): done
# Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda2/envs/stamp

  added / updated specs:
    - pyqt=4


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pyqt-4.10.4                |           py27_0         3.5 MB  asmeurer
    qt-4.8.6                   |                1        38.8 MB  asmeurer
    sip-4.16.3                 |           py27_0         208 KB  asmeurer
    ------------------------------------------------------------
                                           Total:        42.5 MB

The following NEW packages will be INSTALLED:

  pyqt               asmeurer/osx-64::pyqt-4.10.4-py27_0
  qt                 asmeurer/osx-64::qt-4.8.6-1
  sip                asmeurer/osx-64::sip-4.16.3-py27_0

Downloading and Extracting Packages
sip-4.16.3           | 208 KB    | ################################################################################################################## | 100% 
pyqt-4.10.4          | 3.5 MB    | ################################################################################################################## | 100% 
qt-4.8.6             | 38.8 MB   | ################################################################################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

STAMP
/opt/anaconda2/envs/stamp/lib/python2.7/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: The mpl_toolkits.axes_grid module was deprecated in version 2.1. Use mpl_toolkits.axes_grid1 and mpl_toolkits.axisartist provies the same functionality instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)

##returns some warning but STAMP window opened and seems to work fine (for now).
Thanks!
