### ISSUE TITLE
Error in STAMP Website

### ISSUE THREAD

**Issue by ColleenCompas** [dparks1134/STAMP#33]
When I go to http://kiwi.cs.dal.ca/Software/index.php/STAMP the website destination will not load and my browser gives a "This site can’t be reached" error. I have tried loading this page on multiple PCs, but I have received the same error. I was wondering if this page is temporarily down due to maintenance or if it is another issue. Thank you!

**Comment by dparks1134** [comment]
The sever running this site has had to be retired. We hope to move the content of this page over to GitHub in the next few weeks.
