### ISSUE TITLE
Question Regarding Resulting Mean Proportion

### ISSUE THREAD

**Issue by ColleenCompas** [dparks1134/STAMP#35]
Hello,

I have a question in regard to the mean proportion. What is STAMP measuring by using mean proportion? For our data, we are measuring abundances of sequences dedicated to certain biological pathways.
![mean proportion](https://user-images.githubusercontent.com/53987583/73485499-ca6ca900-4368-11ea-9c65-722fad3686da.png)

**Comment by donovan-h-parks** [comment]
Hi. The mean proportion is taken over all samples in a group. If a group has 10 samples, it would be the mean of a particular feature over these 10 samples.

**Comment by ColleenCompas** [comment]
Thank you for your prompt reply! I also have a question in regard to relative frequency. I have four groups that I am analyzing and the relative frequency is not adding to 100% when I am viewing a heatmap of these results. Is there a reason for this?

**Comment by donovan-h-parks** [comment]
Hi. My research direction has changed since I wrote STAMP, so I haven't used it in awhile. Remind me what the heatmap shows? If it is the mean relative frequency of each group, then there is no reason why there should sum to 100%. Example with two groups: [0.1, 0.2], [0.3, 0.4]. All samples add up to 100%, the mean for each group is 0.15 +0.35 = 0.5.

**Comment by ColleenCompas** [comment]
Our heatmap gives the options of showing either the number of sequences per sample or the proportion of sequences (%) per sample.  I currently have the field option set as proportion of sequences. To sort the rows, we chose the mean abundance option and to sort the columns we have chosen the alphabetical order option to order the mice by their respective genotype group.

**Comment by donovan-h-parks** [comment]
I'd have to see the heatmap. Are any of the features (e.g. taxa) being filter out of the visualization to make it more manageable? This would be my initial guess at why all features in a sample don't sum to 100%. Also is any unclassified reads shown in the heatmap? Can this account for the features shown not summing to 100%?

**Comment by ColleenCompas** [comment]
I have sent a message to donovan.parks@gmail.com to show you the settings I have in place for the heatmap and the resulting statistics table that appears.
